language: csharp

matrix:
  include:
    - os: linux # Ubuntu 14.04
      dist: trusty
      sudo: required
      mono: latest
      dotnet: latest
    - os: osx # OSX 10.11
      osx_image: latest
      mono: latest
      dotnet: latest

script:
  - dotnet --info
  - ./build.sh RunTests.NetCore